<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="scout_mini">
  <xacro:arg name="robot_namespace" default="/"/>
  <xacro:include filename="$(find scout_description)/urdf/wheel.xacro"/>

  <!-- Variables -->
  <xacro:property name="M_PI" value="3.14159"/>

  <!-- Vehicle Geometries -->
  <xacro:property name="base_x_size" value="0.6200000"/>
  <xacro:property name="base_y_size" value="0.585000"/>
  <xacro:property name="base_z_size" value="0.235000"/>
  <xacro:property name="wheelbase" value="0.463951"/>
  <xacro:property name="track" value="0.416503"/>
  <xacro:property name="wheel_vertical_offset" value="-0.100998"/>
  <xacro:property name="wheel_diameter" value="0.16"/>
  <xacro:property name="wheel_width" value="0.084"/>
  <xacro:property name="wheel_length" value="0.8e-01"/>
  <xacro:property name="wheel_radius" value="1.600e-01"/>

  <link name="base_link">
    <inertial>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
      <mass value="10"/>
      <inertia ixx="0.1354" ixy="0" ixz="0" iyy="0.1354" iyz="0" izz="0.2667"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0.0" rpy="${M_PI/2} 0 -${M_PI/2}"/>
      <geometry>
        <mesh filename="package://scout_description/meshes/scout_mini_base_link2.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <!-- <mesh
              filename="package://scout_description/meshes/scout_mini_base_link2.dae" /> -->
        <box size="0.4 0.4 0.05"/>
      </geometry>
    </collision>
  </link>
  <link name="box_link">
    <inertial>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 3.14159"/>
      <mass value="5"/>
      <inertia ixx="0.054166666667" ixy="0" ixz="0" iyy="0.075" iyz="0" izz="0.054166666667"/>
    </inertial>
    <visual>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <mesh filename="package://scout_description/meshes/box-parts/box.stl"/>
      </geometry>
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0.1" rpy="${M_PI/2} 0 ${M_PI/2}"/>
      <geometry>
        <box size="0.3 0.2 0.3"/>
      </geometry>
    </collision>
  </link>
  <joint name="box_joint" type="fixed">
    <origin xyz="0 0 0.055" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="box_link"/>
  </joint>

  <link name="laser_link">
    <visual>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <mesh filename="package://scout_description/meshes/box-parts/lidar.stl"/>
      </geometry>
      <material name="cyan">
        <color rgba="0 0.5 1 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0.31" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.06" length="0.1"/>
      </geometry>
    </collision>
  </link>
  <joint name="laser_joint" type="fixed">
    <origin xyz="0.015732 -0.001804 0.200816" rpy="0 0 0"/>
    <parent link="box_link"/>
    <child link="laser_link"/>
  </joint>

  <link name="camera_link">
    <inertial>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia ixx="0.0088463" ixy="2.0356E-05" ixz="-0.00047464" iyy="0.0066478" iyz="-6.9288E-06" izz="0.01219"/>
    </inertial>
    <visual>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <mesh filename="package://scout_description/meshes/box-parts/camera.stl"/>
      </geometry>
      <material name="red">
        <color rgba="1 0 0 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0.31" rpy="0 0 0"/>
      <geometry>
        <box size="0.01 0.01 0.01"/>
      </geometry>
    </collision>
  </link>
  <joint name="camera_joint" type="fixed">
    <origin xyz="0.192646 -0.001255 0.096" rpy="0 0 0"/>
    <parent link="box_link"/>
    <child link="camera_link"/>
  </joint>

  <link name="camera_optical_link"/>
  <joint name="camera_optical_joint" type="fixed">
    <origin xyz="0.01495 0 0.0125" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_optical_link"/>
  </joint>

  <link name="monitor_link">
    <inertial>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia ixx="0.0088463" ixy="2.0356E-05" ixz="-0.00047464" iyy="0.0066478" iyz="-6.9288E-06" izz="0.01219"/>
    </inertial>
    <visual>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <mesh filename="package://scout_description/meshes/box-parts/monitor.stl"/>
      </geometry>
      <material name="purple">
        <color rgba="1 0 1 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0.31" rpy="0 0 0"/>
      <geometry>
        <box size="0.01 0.01 0.01"/>
      </geometry>
    </collision>
  </link>
  <joint name="monitor_joint" type="fixed">
    <origin xyz="-0.088892 -0.001255 0.101303" rpy="0 0 0"/>
    <parent link="box_link"/>
    <child link="monitor_link"/>
  </joint>

  <!-- Scout wheel macros -->
  <xacro:wheel wheel_prefix="front_left" wheel_diameter="${wheel_diameter}" wheel_width="${wheel_width}" axis="1">
    <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="-${M_PI/2} 0 0"/>
  </xacro:wheel>
  <xacro:wheel wheel_prefix="rear_left" wheel_diameter="${wheel_diameter}" wheel_width="${wheel_width}" axis="1">
    <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="-${M_PI/2} 0 0"/>
  </xacro:wheel>
  <xacro:wheel wheel_prefix="front_right" wheel_diameter="${wheel_diameter}" wheel_width="${wheel_width}" axis="-1">
    <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="${M_PI/2} 0 0"/>
  </xacro:wheel>
  <xacro:wheel wheel_prefix="rear_right" wheel_diameter="${wheel_diameter}" wheel_width="${wheel_width}" axis="-1">
    <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="${M_PI/2} 0 0"/>
  </xacro:wheel>

  <!-- Gazebo sim definitions  -->
  <xacro:include filename="$(find scout_description)/urdf/sim.gazebo"/>
</robot>
