<?xml version="1.0"?>
<!--
Software License Agreement (BSD)

\file      scout_wheel.xacro (adapted from wheel.urdf.xacro in husky_description)
\authors   Paul Bovbel <pbovbel@clearpathrobotics.com>
           Ruixiang Du <ruixiang.du@westonrobot.com>
\copyright Copyright (c) 2015, Clearpath Robotics, Inc., All rights reserved.
\copyright Copyright (c) 2020, Weston Robot Pte. Ltd., All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that
the following conditions are met:
 * Redistributions of source code must retain the above copyright notice, this list of conditions and the
   following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
   following disclaimer in the documentation and/or other materials provided with the distribution.
 * Neither the name of Clearpath Robotics nor the names of its contributors may be used to endorse or promote
   products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WAR-
RANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, IN-
DIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="scout_wheel">

  <xacro:macro name="scout_mini_wheel" params="wheel_prefix wheel_diameter wheel_width axis *joint_pose">
    <xacro:property name="wheel_radius" value="${wheel_diameter / 2}" />
            <link name="${wheel_prefix}_wheel_link">
            <inertial>
                <mass value="3" />
                <origin xyz="0 0 0" />
                <inertia 
                    ixx="0.006564" ixy="0" ixz="0"
                    iyy="0.006564" iyz="0" 
                    izz="0.0096"/>
              </inertial>                
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <mesh filename="package://scout_description/meshes/wheel.dae" />
                </geometry>
            </visual>
            <collision>
              <origin
                xyz="0 0 0.03"
                rpy="0 0 0" />
              <geometry>
                <!-- <mesh
                  filename="package://scout_description/meshes/wheel.dae" /> -->
                  <cylinder radius="0.08" length="0.084"/>

              </geometry>
            </collision>
        </link>

        <joint name="${wheel_prefix}_wheel" type="continuous">
            <!--<origin
                  xyz="0.14547 0.20835 -0.07424"
                  rpy="0 1.57 0" />-->
            <parent link="base_link"/>
            <child link="${wheel_prefix}_wheel_link"/>
            <xacro:insert_block name="joint_pose"/>
            <axis xyz="0 0 ${axis}" rpy="0 0 0" />

            <dynamics damping="0.0" friction="0.0"/>
            <limit effort="1000" velocity="20"/>  <!-- High limits for fast turns -->

        </joint>

<gazebo reference="rear_left_wheel">
  <mu1>200.0</mu1>  <!-- High for no longitudinal slip (propulsion) -->
  <mu2>200.0</mu2>  <!-- High for lateral grip during turns (prevents sliding) -->
  <slip1>0.01</slip1>  <!-- Small torsional slip for realism/stability -->
  <slip2>0.01</slip2>  <!-- Lateral slip; tune higher (0.1) if turns feel too sticky -->
  <kp>1e7</kp>      <!-- Stiffness: prevents sinking -->
  <kd>10.0</kd>     <!-- Damping: reduces bounce; increased from 1.0 -->
  <fdir1>1 0 0</fdir1>
  <minDepth>0.005</minDepth>  <!-- Deeper contacts for better force transmission -->
  <maxContacts>10</maxContacts>
</gazebo>
    </xacro:macro>

</robot>
